## Importando a base de dados

In [4]:
import pandas as pd

In [5]:
treino = pd.read_csv('train.csv')
treino.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [6]:
!pip install ydata-profiling

Requirement already satisfied: ydata-profiling in x:\anaconda\lib\site-packages (4.18.1)
Requirement already satisfied: scipy<1.17,>=1.8 in x:\anaconda\lib\site-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in x:\anaconda\lib\site-packages (from ydata-profiling) (2.3.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in x:\anaconda\lib\site-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in x:\anaconda\lib\site-packages (from ydata-profiling) (2.12.4)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in x:\anaconda\lib\site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in x:\anaconda\lib\site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in x:\anaconda\lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in x:\anaconda\lib\site-packages (from ydata-profiling) (2.3.5)
Requirement already satisfied: minify-html>=0.15.0 in x:\anaconda\lib\site-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in x:\anaconda\lib\site-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in x:\anaconda\lib\site-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in x:\anaconda\lib\site-packages (from ydata-profiling) (2.32.5)
Requirement already satisfied: tqdm<5,>=4.66.3 in x:\anaconda\lib\site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in x:\anaconda\lib\site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in x:\anaconda\lib\site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in x:\anaconda\lib\site-packages (from ydata-profiling) (0.14.5)
Requirement already satisfied: typeguard<5,>=4 in x:\anaconda\lib\site-packages (from ydata-profiling) (4.5.1)
Requirement already satisfied: imagehash==4.3.2 in x:\anaconda\lib\site-packages (from ydata-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in x:\anaconda\lib\site-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in x:\anaconda\lib\site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in x:\anaconda\lib\site-packages (from ydata-profiling) (0.62.1)
Requirement already satisfied: PyWavelets in x:\anaconda\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in x:\anaconda\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (12.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in x:\anaconda\lib\site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in x:\anaconda\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in x:\anaconda\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in x:\anaconda\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in x:\anaconda\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.9)
Requirement already satisfied: packaging>=20.0 in x:\anaconda\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in x:\anaconda\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in x:\anaconda\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in x:\anaconda\lib\site-packages (from numba<0.63,>=0.60->ydata-profiling) (0.45.1)
Requirement already satisfied: pytz>=2020.1 in x:\anaconda\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in x:\anaconda\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in x:\anaconda\lib\site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.2)
Requirement already satisfied: annotated-types>=0.6.0 in x:\anaconda\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in x:\anaconda\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in x:\anaconda\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in x:\anaconda\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in x:\anaconda\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in x:\anaconda\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in x:\anaconda\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in x:\anaconda\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2025.11.12)
Requirement already satisfied: patsy>=0.5.6 in x:\anaconda\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: colorama in x:\anaconda\lib\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in x:\anaconda\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.4.0)
Requirement already satisfied: networkx>=2.4 in x:\anaconda\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.5)
Requirement already satisfied: puremagic in x:\anaconda\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (2.2.0)
Requirement already satisfied: six>=1.5 in x:\anaconda\lib\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)

## Criando um relatório usando ydata_profiling

In [7]:
from ydata_profiling import ProfileReport

In [8]:
profile =  ProfileReport(treino, title="titanic_treino")

In [9]:
profile.to_file("titanic_treino.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]
100%|██████████| 12/12 [00:00<00:00, 97.67it/s][A

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

## Analisando a base

In [10]:
treino.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [11]:
# Verificando o tipo de dados
treino.dtypes.value_counts()

int64      5
object     5
float64    2
Name: count, dtype: int64

In [12]:
# Verificando os valores nulos
treino.isnull().sum().sort_values(ascending=False).head(5)

Cabin          687
Age            177
Embarked         2
PassengerId      0
Survived         0
dtype: int64

## Visualizando a base de teste

In [13]:
teste = pd.read_csv('test.csv')
teste.head(3)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q

In [14]:
teste.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB

In [15]:
teste.isnull().sum().sort_values(ascending=False).head(5)

Cabin          327
Age             86
Fare             1
PassengerId      0
Pclass           0
dtype: int64

> **Observação:** Existem colunas que possuem valores vazios na base de teste que não estão vazias na base de treino (nesse caso, precisa tratar essas colunas apenas na base de teste).

## Realizando os tratamentos iniciais dos dados

In [16]:
treino.isnull().sum().sort_values(ascending=False).head(5)

Cabin          687
Age            177
Embarked         2
PassengerId      0
Survived         0
dtype: int64

In [17]:
# Retornando o shape (dimensão da tabela = linhas, colunas)
treino.shape

(891, 12)

In [18]:
treino.head(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [19]:
# Verificando a cardinalidade (quantiade de valores únicos em uma coluna) dos dados.
treino.nunique().sort_values(ascending=False)

PassengerId    891
Name           891
Ticket         681
Fare           248
Cabin          147
Age             88
SibSp            7
Parch            7
Pclass           3
Embarked         3
Survived         2
Sex              2
dtype: int64

**Observação:** Colunas com alta cardinalidade como nome, número do ticket e até mesmo o código da cabine não vão ajudar o modelo pois podem torná-los menos generalizável. Nesse caso, elimina essas colunas.

In [20]:
# Eliminando para base de treino
treino = treino.drop(['Name', 'Ticket', 'Cabin'], axis=1)

In [21]:
# Eliminando, também, na base de teste
teste = teste.drop(['Name', 'Ticket', 'Cabin'], axis=1)

**Observação:** Precisa tratar a coluna Age, que possui valores vazios tanto no treino quanto no teste. Como essa coluna possui a idade dos passageiros, utiliza-se a média das idades para substituir os valores vazios.

In [22]:
# Verificando a média das idades para a base de treino
treino.Age.mean()

np.float64(29.69911764705882)

In [23]:
# Selecionando as colunas com idade vazia e substituindo pela média
treino.loc[treino.Age.isnull(),'Age'] = treino.Age.mean()

In [24]:
# O mesmo para a base de teste
teste.loc[teste.Age.isnull(),'Age'] = teste.Age.mean()

**Observação:** Na base de treino, ainda tem 2 valores vazios na coluna Embarked. Verificar todos os valores nessa coluna e substituir os valores vazios pela moda.

In [25]:
# Verificando os valores na coluna Embarked
treino.Embarked.value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [26]:
# Selecionando a moda dessa coluna
treino.Embarked.mode()[0]

'S'

In [27]:
# Substituindo os valores vazios
treino.loc[treino.Embarked.isnull(),'Embarked'] = treino.Embarked.mode()[0]

**Observação:** A coluna Fare ainda tem 1 valor vazio. Pode ser usado a mesma ideia que foi feito para a coluna Age e substituindo pela moda.

In [28]:
# Verificando a média da coluna fare para a base de teste
teste.loc[teste.Fare.isnull(),'Fare'] = teste.Fare.mean()

## Verificando os valores vazios novamente

In [29]:
# Na base de treino
treino.isnull().sum().sort_values(ascending=False).head(5)

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
dtype: int64

In [30]:
# Na base de teste
teste.isnull().sum().sort_values(ascending=False).head(5)

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
dtype: int64

## Considerando apenas as colunas que não são de texto

In [31]:
# Verificando as colunas de texto
col_treino_nr = treino.columns[treino.dtypes != 'object']
col_treino_nr

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [32]:
# Selecionando apenas os valores númericos da base de treino
treino_nr = treino.loc[:,col_treino_nr]

In [33]:
# Na base de teste
col_teste_nr = teste.columns[teste.dtypes != 'object']
col_teste_nr

Index(['PassengerId', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [34]:
# Valores númericos da base de teste
teste_nr = teste.loc[:,col_teste_nr]

## Testando modelos para classificar esses dados

### Separando a base de treino em treino e validação usando o train_test_split

In [35]:
from sklearn.model_selection import train_test_split

In [41]:
# Separando a base de treino em x e y
X = treino_nr.drop(['PassengerId', 'Survived'], axis=1)
y = treino.Survived

In [42]:
# Separando em treino e validação
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.33, random_state=42)

### Usando a árvore de classificação

**Observação:**  prevê a categoria (classe) de um dado através de uma série de perguntas "se-então". </br>
https://scikit-learn.org/stable/modules/tree.html

In [43]:
# Fazendo a importação
from sklearn import tree

In [47]:
# Criando o classificador
clf_ac = tree.DecisionTreeClassifier(random_state=42)

In [56]:
# Fazendo fit com os dados
clf_ac = clf_ac.fit(X_train, y_train)

In [57]:
# Fazendo a previsão
y_pred_ac = clf_ac.predict(X_val)

### Usando KNeighborsClassifier

**Observação:** KNN é um algoritmo que classifica um novo dado com base nos rótulos dos K exemplos mais próximos a ele. </br> https://scikit-learn.org/stable/modules/neighbors.html

In [54]:
# Importando
from sklearn.neighbors import KNeighborsClassifier

In [55]:
# Criando o classificador
clf_knn = KNeighborsClassifier(n_neighbors=3)

In [58]:
# Fazendo o fit com os dados
clf_knn = clf_knn.fit(X_train, y_train)

In [59]:
# Fazendo a previsão
y_pred_knn = clf_knn.predict(X_val)

### Usando a Regressão Logistica

**Observação:** Regressão logística funciona calculando uma combinação dos dados de entrada e transformando isso em uma probabilidade entre 0 e 1 para decidir a classe. </br>https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

In [60]:
# Importando
from sklearn.linear_model import LogisticRegression

In [61]:
# Criando o classificador
clf_r1 = LogisticRegression(random_state=42)

In [63]:
# Fazendo o fit com os dados
clf_r1 = clf_r1.fit(X_train, y_train)

In [64]:
# Fazendo a previsão
y_pred_r1 = clf_r1.predict(X_val)

## Avaliando modelos

### Acurácia

In [66]:
# Importando
from sklearn.metrics import accuracy_score

In [67]:
# Para a árvore
accuracy_score(y_val, y_pred_ac)

0.6169491525423729

In [73]:
# Para o Knn
accuracy_score(y_val, y_pred_knn)

0.6542372881355932

In [74]:
# Para a Regressão Logística
accuracy_score(y_val, y_pred_r1)

0.7254237288135593

### Avaliando a matriz de confunsão 
**Tabela que compara as previsões do modelo com os valores reais, mostrando acertos e erros por classe.**

In [72]:
# Importando
from sklearn.metrics import confusion_matrix

In [75]:
# Para a árvore
confusion_matrix(y_val, y_pred_ac)

array([[125,  50],
       [ 63,  57]])

In [76]:
# Para o Knn
confusion_matrix(y_val, y_pred_knn)

array([[133,  42],
       [ 60,  60]])

In [77]:
# Para a Regressão Logística
confusion_matrix(y_val, y_pred_r1)

array([[156,  19],
       [ 62,  58]])

## Fazendo previsão para os dados de teste

In [78]:
# Visualizando o X_train
X_train.head(3)

     Pclass        Age  SibSp  Parch     Fare
6         1  54.000000      0      0  51.8625
718       3  29.699118      0      0  15.5000
685       2  25.000000      1      2  41.5792

In [80]:
# Visualizando a base de teste (apenas com valores numericos)
teste_nr.head(3)

   PassengerId  Pclass   Age  SibSp  Parch    Fare
0          892       3  34.5      0      0  7.8292
1          893       3  47.0      1      0  7.0000
2          894       2  62.0      0      0  9.6875

In [81]:
# Para a base de teste ser igual a base de treino, precisamos eliminar a coluna id
X_teste = teste_nr.drop("PassengerId", axis=1)

In [82]:
# Usando regressão logistica na base de teste
y_pred = clf_r1.predict(X_teste)

In [84]:
# Crinado uma nova coluna com a previsão na base de teste
teste['Survived'] = y_pred

In [86]:
# Selecionando apenas a coluna de Id e Survived para fazer o envio
base_envio = teste[['PassengerId', 'Survived']]

In [87]:
# Exportando para um csv
base_envio.to_csv('resultados1.csv', index=False)